[build]
builder = "nixpacks"

[deploy]
startCommand = "python src/main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PORT = "5000" 